[project]
name = 'Plastix'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Plastix]
path = 'contracts/Plastix.clar'
clarity_version = 3
epoch = 3.1
[contracts.carbon-credits]
path = 'contracts/carbon-credits.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
